version: "3.9"

services:
  pg:
    image: postgres:18
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.prod
    container_name: fastapi-api-prod
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://shop:shop@pg:5432/shop
      APP_CONFIG__DB__ECHO: "0"
    depends_on:
      - pg
    ports:
      - "8000:8000"

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile.prod
    container_name: vue_frontend_prod
    depends_on:
      - api

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy_prod
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - client

volumes:
  pgdata:
