version: "3.9"

services:
  pg:
    image: postgres:18
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shop -d shop"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: fastapi-api
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://shop:shop@pg:5432/shop
      APP_CONFIG__DB__ECHO: "0"
      DEV: "1"                     # <-- включаем dev-режим (reload) внутри контейнера
    depends_on:
      - pg
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app                 # синхронизируем код api с контейнером
      - /app/.venv                 # изолируем виртуальное окружение в контейнере
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    container_name: vue_frontend
    command: yarn dev --host 0.0.0.0
    environment:
      - CHOKIDAR_USEPOLLING=true   # в контейнере полезно для некоторых ОС
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app              # синхронизируем код фронта              
    depends_on:
      - api

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/nginx/certs:ro
    depends_on:
      - api
      - client

volumes:
  pgdata:
